remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin : "mint"
plugins:
  - jekyll-include-cache
  
# Site Settings
locale                   : "en-US"
title                    : "Info Vis"
title_separator          : "-"
subtitle                 : "ITBA"
name                     : "Micaela Banfi"
description         : "Bienvenidos! Aca podran encontrar los trabajos de la materia"
url: "https://micabanfi.github.io/infovis/"

# Site Author
author:
  name             : "Micaela Banfi"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "software engineer in the process"
  location         : "Buenos Aires, Argentina"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mbanfi@itba.edu.ar"


# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/micabanfi"



