theme: jekyll-theme-architect
title: InfoVis ITBA
description: Bienvenidos! Aca podran encontrar los trabajos de la materia
author: Micaela Banfi
title-img: "https://github.com/micabanfi/infovis/img/me.jpg"
