theme: jekyll-theme-minimal
minimal_mistakes_skin : "mint"

locale                   : "en-US"
title                    : "InfoVis"
title_separator          : "-"
subtitle                 : "ITBA"
name                     : "Micaela Banfi"
description              : "Bienvenidos! Aca podran encontrar los trabajos de la materia"



