remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin : "mint"

# Site Settings
locale                   : "en-US"
title                    : "Info Vis"
title_separator          : "-"
subtitle                 : "ITBA"
name                     : "InfoVis ITBA"
description              : "Bienvenidos! Aca podran encontrar los trabajos de la materia"
url: "https://micabanfi.github.io/infovis/"




